/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bowl.GUI;

import com.mycompany.bowl.backend.lenguaje.sintactico.pilas.muestra.Muestra;
import com.mycompany.bowl.backend.lenguaje.sintactico.pilas.muestra.PilaMuestra;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 * @author mari2bar
 */
public class PilaFrame extends javax.swing.JFrame {

    private BowlGUI bowl;

    /**
     * Creates new form PilaFrame
     *
     * @param bowl
     */
    public PilaFrame(BowlGUI bowl) {
        initComponents();
        this.bowl = bowl;
        pnlEstado.setLayout(null);
        pnlNodos.setLayout(null);
        this.setLocationRelativeTo(bowl);
        this.setTitle("Pila");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblOperacion = new javax.swing.JLabel();
        pnlPila = new javax.swing.JPanel();
        lblNodo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        spEstado = new javax.swing.JScrollPane();
        pnlEstado = new javax.swing.JPanel();
        spNodo = new javax.swing.JScrollPane();
        pnlNodos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        lblOperacion.setFont(new java.awt.Font("URW Bookman", 1, 14)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(255, 255, 255));

        pnlPila.setBackground(new java.awt.Color(102, 102, 102));

        lblNodo.setForeground(new java.awt.Color(255, 255, 255));
        lblNodo.setText("Nodos");

        lblEstado.setForeground(new java.awt.Color(255, 255, 255));
        lblEstado.setText("Numero Estado");

        javax.swing.GroupLayout pnlEstadoLayout = new javax.swing.GroupLayout(pnlEstado);
        pnlEstado.setLayout(pnlEstadoLayout);
        pnlEstadoLayout.setHorizontalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        pnlEstadoLayout.setVerticalGroup(
            pnlEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        spEstado.setViewportView(pnlEstado);

        javax.swing.GroupLayout pnlNodosLayout = new javax.swing.GroupLayout(pnlNodos);
        pnlNodos.setLayout(pnlNodosLayout);
        pnlNodosLayout.setHorizontalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        pnlNodosLayout.setVerticalGroup(
            pnlNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        spNodo.setViewportView(pnlNodos);

        javax.swing.GroupLayout pnlPilaLayout = new javax.swing.GroupLayout(pnlPila);
        pnlPila.setLayout(pnlPilaLayout);
        pnlPilaLayout.setHorizontalGroup(
            pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstado)
                    .addComponent(spEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spNodo)
                    .addComponent(lblNodo))
                .addContainerGap())
        );
        pnlPilaLayout.setVerticalGroup(
            pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPilaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spEstado)
                    .addComponent(spNodo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSiguiente)))
                .addContainerGap())
            .addComponent(pnlPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(lblOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (entero < muestra.getMuestra().size()) {
            entero++;
            this.realizarPanel();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        if (entero > 0) {
            entero--;
            this.realizarPanel();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private int entero;
    private PilaMuestra muestra;

    public void iniciarPanel() {
        muestra = bowl.getSeleccionado().getLenguaje().getAnalisis().getPila().getMuestra();
        entero = 0;
        this.realizarPanel();
    }

    public void realizarPanel() {
        if (entero < muestra.getMuestra().size() && entero >= 0) {
            Muestra ms = muestra.getMuestra().get(entero);
            int tam = Integer.max(ms.getEnteros().size(), ms.getString().size());
            pnlEstado.removeAll();
            pnlNodos.removeAll();
            pnlEstado.setPreferredSize(new Dimension(180, 50 * tam));
            pnlNodos.setPreferredSize(new Dimension(180, 50 * tam));
            for (int i = 0; i < ms.getEnteros().size(); i++) {
                JLabel nuevo = new JLabel();
                nuevo.setSize(new Dimension(170, 50));
                nuevo.setForeground(Color.white);
                nuevo.setBackground(Color.BLACK);
                nuevo.setOpaque(true);
                nuevo.setBorder(new LineBorder(Color.BLACK, 2, true));
                nuevo.setFont(new Font(Font.MONOSPACED, Font.ROMAN_BASELINE, 14));
                nuevo.setVisible(true);
                nuevo.setText("  --" + String.valueOf(ms.getEnteros().get(i)));
                nuevo.setLocation(5, 50 * tam - ((i + 1) * 50));
                pnlEstado.add(nuevo);
            }
            for (int i = 0; i < ms.getString().size(); i++) {
                JLabel nuevo = new JLabel();
                nuevo.setSize(new Dimension(170, 50));
                nuevo.setForeground(Color.white);
                nuevo.setBackground(Color.BLACK);
                nuevo.setOpaque(true);
                nuevo.setBorder(new LineBorder(Color.BLACK, 2, true));
                nuevo.setFont(new Font(Font.MONOSPACED, Font.ROMAN_BASELINE, 14));
                nuevo.setVisible(true);
                nuevo.setText(" --"+ms.getString().get(i));
                nuevo.setLocation(5, 50 * tam - ((i + 1) * 50));
                pnlNodos.add(nuevo);
            }
            pnlEstado.repaint();
            pnlNodos.repaint();
            this.lblOperacion.setText(ms.getAccion());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNodo;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JPanel pnlEstado;
    private javax.swing.JPanel pnlNodos;
    private javax.swing.JPanel pnlPila;
    private javax.swing.JScrollPane spEstado;
    private javax.swing.JScrollPane spNodo;
    // End of variables declaration//GEN-END:variables
}
