/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bowl.GUI;

import com.mycompany.bowl.backend.lenguaje.Lenguaje;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mari2bar
 */
public class TablaHTML extends javax.swing.JFrame {

    private BowlGUI bowl;

    /**
     * Creates new form TablaHTML
     *
     * @param bowl
     */
    public TablaHTML(BowlGUI bowl) {
        initComponents();
        this.bowl = bowl;
        editorHTML.setEditable(false);
        this.setLocationRelativeTo(bowl);
        this.setTitle("Tabla LALR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorHTML = new javax.swing.JEditorPane();

        jScrollPane1.setViewportView(editorHTML);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarTabla(Lenguaje lenguaje) {
        this.setLocationRelativeTo(bowl);
        try {
            ClassLoader classLoader = getClass().getClassLoader();
            File file = new File(classLoader.getResource("tabla/").getFile()), file2;
            System.out.println(file.getPath());
            file2 = new File(file.getPath()+"/tabla.html");
            System.out.println(file2.getPath());
            if (!file2.exists()) {
                file2.createNewFile();
            }
            FileWriter fichero = null;
            PrintWriter pw = null;
            fichero = new FileWriter(file2);
            pw = new PrintWriter(fichero);
            pw.println(lenguaje.getTablaLALR().getTabla());
            pw.close();
            editorHTML.setPage(file2.toURI().toURL());
            Desktop.getDesktop().open(file2);
        } catch (IOException ex) {
            Logger.getLogger(TablaHTML.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorHTML;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
